### ISSUE TITLE
Can not install crates on Firefox

### ISSUE THREAD

**Issue by AurevoirXavier** [huhu/rust-search-extension#114]
<img width="225" alt="image" src="https://user-images.githubusercontent.com/16152305/115956340-bf360800-a52e-11eb-8caa-de6230f4742a.png">

But once I refresh the page.

<img width="227" alt="image" src="https://user-images.githubusercontent.com/16152305/115956362-d37a0500-a52e-11eb-8d46-3cc810a13c3a.png">

**Comment by Folyd** [comment]
Hi, thanks for the feedback. Which crate failed to be installed?

**Comment by AurevoirXavier** [comment]
> Hi, thanks for the feedback. Which crate failed to be installed?

syn

**Comment by AurevoirXavier** [comment]
https://docs.rs/syn/1.0.70/syn/parse/index.html

**Comment by Folyd** [comment]
> > Hi, thanks for the feedback. Which crate failed to be installed?
> 
> syn
> 
> https://docs.rs/syn/1.0.70/syn/parse/index.html

This is a bug, due to the new search-index.js on-demand load mode which introduced in [#82310](https://github.com/rust-lang/rust/pull/82310). I'll fix this ASAP.

Currently, a possible workaround:
- Click the docs.rs's search box in advance (this will trigger the search-index load)
- Click `+ to Rust Search Extension` button

**Comment by Folyd** [comment]
A new version (v1.2.1) has been released. This should be fixed.
