### ISSUE TITLE
Statistics appear to get lost

### ISSUE THREAD

**Issue by piegamesde** [huhu/rust-search-extension#131]
That'd be really interesting to have a look at IMO. Sadly, at the moment only the last month appears to be kept.

**Comment by Folyd** [comment]
Actually, we kept all statistics data since your first search. The statistics chart was inspired by GitLab's [repository analytics](https://docs.gitlab.com/ee/user/analytics/repository_analytics.html), which shows the statistics since your first commit. 

![image](https://user-images.githubusercontent.com/3369694/139693463-74dc7ffc-4f02-4786-aa29-8e72b0899a49.png)

However, we can group the statistics by month or year. But that is not in my plan in the recent future.

**Comment by piegamesde** [comment]
So apparently it keeps more than one month of statistics, but not enough: my the data goes back to August 9th for me, although I already use this extension since it publicly launched.

**Comment by Folyd** [comment]
Hi @piegamesde. What is your environment? Firefox or Chrome? Did you uninstall the extension and reinstall it in the past? I have occurred a data loss after I upgrade my Chrome. 

I can't promise 100% data persistence since we never sync your data to the server. A suboptimal way is to export your data into your local file regularly.
