### ISSUE TITLE
AMO version suddenly requires access to all websites

### ISSUE THREAD

**Issue by Jokler** [huhu/rust-search-extension#190]
It just popped up today and when reinstalling I am presented with this:
![ss_20220815-0255](https://user-images.githubusercontent.com/5204415/184561777-320b5d2d-b1e8-432c-93d7-b6bb67f9ef8d.png)

The FAQ only explains the need for github.com and the permissions list on AMO only lists 3 specific sites which are accessed so what exactly is going on here?

**Comment by Folyd** [comment]
Oh, Firefox is overwhelmed. Actually, the only additional permission required is `file:///*`, see https://github.com/huhu/rust-search-extension/blob/master/manifest.jsonnet#L79. We need `file:///*` because we integrate `macro_railroad`, which can display railroad diagrams for your local docs. I'll remove the `file:///*` since it not working on Manifest V3. See also #189.

**Comment by jackinloadup** [comment]
Also was curious about this. Thanks for the explanation. 

For SEO:  Access your data for all websites
