### ISSUE TITLE
Bug: Extension opens /update page every browser launch

### ISSUE THREAD

**Issue by RileyMShea** [huhu/rust-search-extension#97]
Every time I open chrome, the rust -search-extension is opening the https://rust.extension.sh/update page in a tab, regardless of any tabs(including itself) that were open on last chrome launch.

Steps to reproduce:
1. Install chrome
2. Install rust-search extension
3. Toggle `Auto-update` to `On`
4. Close all browser windows
5. Re-open Chrome
6. See a https://rust.extension.sh/update tab
7. Repeat steps 4-6 to witness issue persist

![image](https://user-images.githubusercontent.com/10238802/104131726-3eb81680-5346-11eb-8e97-4e3041049871.png)
![image](https://user-images.githubusercontent.com/10238802/104131732-47a8e800-5346-11eb-877e-6f0eaf27d406.png)

OS: Ubuntu 20.04 x64(Linux)
Browser: Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by Folyd** [comment]
Hi @RileyMShea, huge thanks for your feedback. This is an intended design for enabled auto-update right now. You can turn it off if you prefer not to see the update page when your browser launch. In the next version, I'll change to open the update page at most one time a day if the auto-update is on.

**Comment by RileyMShea** [comment]
@Folyd I'm afraid I don't understand why it wouldn't  open only once, after an actual update?  It puts a really bad light on the project unless I'm missing something.

**Comment by Folyd** [comment]
> @Folyd I'm afraid I don't understand why it wouldn't open only once, after an actual update? It puts a really bad light on the project unless I'm missing something.

I don't think only a one-time update is enough since our top 20K crate index and other kinds of stuff will get updated daily by daily. See Github [workflow files](https://github.com/huhu/rust-search-extension/blob/master/.github/workflows/crates-index.yml#L6). Imaging we have a v1.0.1 of `tokio` on the first day. On the second day, we got the v1.0.2 released. If we have no second update, we can't search the latest docs of v1.0.2 in the address bar. 😸

**Comment by enaut** [comment]
Then you'd need a way to enable autoupdate but make the advertizing tab optional... it is really annoying!

**Comment by Folyd** [comment]
> Then you'd need a way to enable autoupdate but make the advertizing tab optional... it is really annoying!
> The only reason why I did not uninstall this immediately is because of the github link.

No, please don't say it is an advertising tab. 😢 This auto-update is not intended for an extension version update, it's for the offline search index instead. Due to the limitation of browser API, it's impossible to perform such an update in silence. The only way to sync the latest search index is to open this update page. However, auto-update is disabled by default. Please don't turn it on if it isn't your want.

**Comment by enaut** [comment]
Oh now I understand... I think you should explain why that page is opened on the said page. Because there are so many "malicious" adons that open ad-tabs... - It must be clear why the tab opened and that this is mandatory and only necessary for the local indexing. Because my reflex whenever an extension opens a tab is to remove that extension - no questions asked... and don't feel sad I appreciate your extension and work! - it was just my perception.

**Comment by Folyd** [comment]
Thanks for your suggestion. I'll clarify the update page soon.
