### ISSUE TITLE
Forced to reinstall extension

### ISSUE THREAD

**Issue by kw-fn** [huhu/rust-search-extension#99]
Over the past couple days: I've twice needed to remove and re-install the extension for search to work properly. Browser is: FF78.6.1esr (64-bit).

**Comment by Folyd** [comment]
Thanks for the feedback. Could you please give me more detail about work improperly? Can't use `rs` to search? Or search something but get nothing result?

**Comment by kw-fn** [comment]
Yeah, thanks for getting back. I can enter `rs` in the address bar and it shows
a single line item by no related results and pressing enter for whatever the
input is merely redirects to the browsers search provider. I restarted my system
today and am again required to reinstall the extension.

**Comment by tdonovan4** [comment]
I ran into the same issue using Firefox 84.0.2. This is the error message I got:
```
Uncaught (in promise) TypeError: rawSearchIndex[crate] is undefined
    buildIndex moz-extension://21a652d7-2f59-4b03-a403-777fc59763ac/search/docs/base.js:82
    DocSearch moz-extension://21a652d7-2f59-4b03-a403-777fc59763ac/search/docs/base.js:43
    NightlySearch moz-extension://21a652d7-2f59-4b03-a403-777fc59763ac/search/docs/std.js:13
    <anonymous> moz-extension://21a652d7-2f59-4b03-a403-777fc59763ac/main.js:34
    async* moz-extension://21a652d7-2f59-4b03-a403-777fc59763ac/main.js:364
base.js:82:17
````
I did some digging and found out that the culprit was the key `index-std-nightly` in the extension 
storage whose value was set to `{proc_macro: undefined, std: undefined, test: undefined}`.

I was able to fix the issue by deleting the key and updating the index. However, it came back 
later and I had to do the manipulation again.

**Comment by Folyd** [comment]
Thanks! This is a bug, I'll fix this ASAP.
